In [1]:
# 1) Import necessary libraries
import pandas as pd
import numpy as np

# (Optional) Display tweaks
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 140)

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.2.2
NumPy: 2.0.2

In [2]:
DATA_PATH = "/content/climate-risk-index-1.csv"

df = pd.read_csv(DATA_PATH, low_memory=False)
print("Loaded shape:", df.shape)
df.head()

Loaded shape: (182, 17)

,index,cartodb_id,the_geom,the_geom_webmercator,country,cri_rank,cri_score,fatalities_per_100k_rank,fatalities_per_100k_total,fatalities_rank,fatalities_total,losses_per_gdp__rank,losses_per_gdp__total,losses_usdm_ppp_rank,losses_usdm_ppp_total,rw_country_code,rw_country_name
0,0,1,NaN,NaN,Saudi Arabia,79,72.50,18,0.45,18,140,131,0.0001,119,1.229,SAU,Saudi Arabia
1,1,2,NaN,NaN,Romania,61,61.50,112,0.01,102,1,16,0.6746,11,2797.884,ROU,Romania
2,2,3,NaN,NaN,Spain,69,66.33,74,0.05,47,22,86,0.0394,31,637.070,ESP,Spain
3,3,4,NaN,NaN,Slovenia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SVN,Slovenia
4,4,5,NaN,NaN,South Sudan,133,117.33,114,0.00,114,0,120,0.0021,122,0.508,SSD,South Sudan

In [3]:
# 3a) .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      182 non-null    int64
 1   cartodb_id                 182 non-null    int64
 2   the_geom                   0 non-null      float64
 3   the_geom_webmercator       0 non-null      float64
 4   country                    182 non-null    object
 5   cri_rank                   182 non-null    int64
 6   cri_score                  182 non-null    float64
 7   fatalities_per_100k_rank   182 non-null    int64
 8   fatalities_per_100k_total  182 non-null    float64
 9   fatalities_rank            182 non-null    int64
 10  fatalities_total           182 non-null    int64
 11  losses_per_gdp__rank       182 non-null    int64
 12  losses_per_gdp__total      131 non-null    float64
 13  losses_usdm_ppp_rank       182 non-null    int64
 14  losses_usdm_ppp_total      182 non-null    float64
 15  rw_country_code            179 non-null    object
 16  rw_country_name            179 non-null    object
dtypes: float64(6), int64(8), object(3)
memory usage: 24.3+ KB

In [4]:
# 3b) .describe()  (numeric columns)
df.describe()

,index,cartodb_id,the_geom,the_geom_webmercator,cri_rank,cri_score,fatalities_per_100k_rank,fatalities_per_100k_total,fatalities_rank,fatalities_total,losses_per_gdp__rank,losses_per_gdp__total,losses_usdm_ppp_rank,losses_usdm_ppp_total
count,182.000000,182.000000,0.0,0.0,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,131.000000,182.000000,182.000000
mean,90.500000,91.500000,NaN,NaN,85.230769,81.791923,78.609890,0.519670,77.626374,86.840659,85.302198,1.517654,85.302198,907.507599
std,52.683014,52.683014,NaN,NaN,44.708529,34.582412,37.858511,3.393934,37.500688,427.350623,44.691600,8.171267,44.691600,4483.998505
min,0.000000,1.000000,NaN,NaN,1.000000,12.170000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000100,1.000000,0.000000
25%,45.250000,46.250000,NaN,NaN,46.250000,52.872500,46.250000,0.000000,46.250000,0.000000,46.250000,0.016500,46.250000,0.000000
50%,90.500000,91.500000,NaN,NaN,91.000000,77.500000,91.500000,0.020000,90.000000,2.000000,91.500000,0.084100,91.500000,30.347000
75%,135.750000,136.750000,NaN,NaN,135.000000,124.500000,114.000000,0.120000,114.000000,22.750000,135.000000,0.275950,135.000000,262.178250
max,181.000000,182.000000,NaN,NaN,135.000000,124.500000,114.000000,43.660000,114.000000,4317.000000,135.000000,77.369400,135.000000,40077.222000

In [5]:
# 3c) .describe(include='all')  (numeric + non-numeric)
df.describe(include='all')

,index,cartodb_id,the_geom,the_geom_webmercator,country,cri_rank,cri_score,fatalities_per_100k_rank,fatalities_per_100k_total,fatalities_rank,fatalities_total,losses_per_gdp__rank,losses_per_gdp__total,losses_usdm_ppp_rank,losses_usdm_ppp_total,rw_country_code,rw_country_name
count,182.000000,182.000000,0.0,0.0,182,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,131.000000,182.000000,182.000000,179,179
unique,NaN,NaN,NaN,NaN,182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179,179
top,NaN,NaN,NaN,NaN,Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAU,Saudi Arabia
freq,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
mean,90.500000,91.500000,NaN,NaN,NaN,85.230769,81.791923,78.609890,0.519670,77.626374,86.840659,85.302198,1.517654,85.302198,907.507599,NaN,NaN
std,52.683014,52.683014,NaN,NaN,NaN,44.708529,34.582412,37.858511,3.393934,37.500688,427.350623,44.691600,8.171267,44.691600,4483.998505,NaN,NaN
min,0.000000,1.000000,NaN,NaN,NaN,1.000000,12.170000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000100,1.000000,0.000000,NaN,NaN
25%,45.250000,46.250000,NaN,NaN,NaN,46.250000,52.872500,46.250000,0.000000,46.250000,0.000000,46.250000,0.016500,46.250000,0.000000,NaN,NaN
50%,90.500000,91.500000,NaN,NaN,NaN,91.000000,77.500000,91.500000,0.020000,90.000000,2.000000,91.500000,0.084100,91.500000,30.347000,NaN,NaN
75%,135.750000,136.750000,NaN,NaN,NaN,135.000000,124.500000,114.000000,0.120000,114.000000,22.750000,135.000000,0.275950,135.000000,262.178250,NaN,NaN
max,181.000000,182.000000,NaN,NaN,NaN,135.000000,124.500000,114.000000,43.660000,114.000000,4317.000000,135.000000,77.369400,135.000000,40077.222000,NaN,NaN

In [6]:
# 3d) .isnull().sum()  (check for missing values)
df.isnull().sum().sort_values(ascending=False)

the_geom                     182
the_geom_webmercator         182
losses_per_gdp__total         51
rw_country_code                3
rw_country_name                3
index                          0
cri_rank                       0
cartodb_id                     0
country                        0
fatalities_per_100k_total      0
fatalities_per_100k_rank       0
cri_score                      0
fatalities_rank                0
losses_per_gdp__rank           0
fatalities_total               0
losses_usdm_ppp_total          0
losses_usdm_ppp_rank           0
dtype: int64